import Head from 'next/head';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>りさのポートフォリオ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className={styles['header']}>
        <nav className={styles['nav']}>
          <ul className={styles['nav-list']}>
            <li>
              <Link href='#'>自己紹介</Link>
            </li>
            <li>
              <Link href='#'>できること</Link>
            </li>
            <li>
              <Link href='#'>制作例</Link>
            </li>
            <li>
              <Link href='#'>お問い合わせ</Link>
            </li>
          </ul>
        </nav>
      </header>
      <main className={`${styles['main']}`}>
        <p>りさ</p>
      </main>
      <footer className={styles['footer']}>
        <p className={styles['copy-light']}>Copyright © 2023 Y pjt All rights reserved,</p>
      </footer>
    </>
  );
}
