import Head from 'next/head'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>りさのポートフォリオ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
<nav>
  <ul>
    
    <li>

    </li>
  </ul>
</nav>
      </header>
      <main className={`${styles['main']}`}>
        <p>りさ</p>
      </main>
      <footer>

      </footer>
    </>
  )
}
